# WebSocket Stress Tester Configuration

# Server connection settings
server:
  host: "xxx.xxx.xxx.x"
  port: 7070
  protocol: "ws"  # ws or wss
  path: "/"

# Connection test settings
test:
  start_connections: 10  # Start with 10 connections
  max_connections: 100   # Test up to 100 connections
  increment: 5           # Add 5 new connections each batch
  batch_duration: 10     # Hold connections open longer to observe behavior
  connection_delay: 0.2  # Small delay between opening connections
  stability_threshold: 90.0  # percentage success rate considered stable
  cumulative_mode: true  # Keep existing connections open when adding new ones 